#!/usr/bin/env python3
import argparse
import requests
import json

def healthcheck(ar):
	headers = {'x-observatory-auth' : ar.apikey}
	res = requests.get('http://localhost:8765/evcharge/api/admin/healthcheck', headers=headers)
	print(res.status_code)
	print(res.json())
	return True


parser = argparse.ArgumentParser()
parser.add_argument('--apikey', help='Give API key', required='TRUE')
args = parser.parse_args()

healthcheck(args)

