#!/usr/bin/env python3
import argparse
import requests
import json

def resetsessions(ar):
	headers = {'x-observatory-auth' : ar.apikey}
    res = requests.post('http://pluganddrive.ddns.net:8765/evcharge/api/admin/resetsessions', headers=headers, verify=False)
    print(res.status_code)
    print(res.json())
    return True


parser = argparse.ArgumentParser()
parser.add_argument('--apikey', help='Give API key', required='TRUE')
args = parser.parse_args()

resetsessions(args)
