#!/usr/bin/env python3
import argparse
import requests
import json
from pathlib import Path
from datetime import date

def sessions_per_provider(ar):
    url = 'http://pluganddrive.ddns.net:8765/evcharge/api/SessionsPerProvider/' + ar.provider + '/' + str(ar.datefrom) + '/' + str(ar.dateto)
    if (ar.format == 'csv'):
        url = url + '?format=csv'
    print(url)
    headers = {'x-access-token' : ar.apikey}
    res = requests.get(url, headers=headers)
    #print(res.status_code)
    #json = res.json() #in reality a python dict
    #print(json)
    #print(json['accessToken'])
    return True


parser = argparse.ArgumentParser()
parser.add_argument('--apikey', help='Give API key', required='TRUE')
parser.add_argument('--format', choices=['csv','json'], help='Choose format (json or csv)', required='TRUE')
parser.add_argument('--datefrom', help='Choose start of period', required='TRUE')
parser.add_argument('--provider', help='Choose provider id', required='TRUE')
parser.add_argument('--dateto', help='Choose end of period', required='TRUE')
args = parser.parse_args()

sessions_per_provider(args)

#print (args)
